### PR TITLE
Cu 86b17nztq implement commands 

### PR DESCRIPTION
**Pull request by hyt152004**
this new implementation doesnt use get_collision. it just works with the distance between the two vehicles and the angle they are both facing.

due to the kinematic equations being used, ALL VEHICLES MUST BE PLACED at least 10m AWAY FROM EACH OTHER AT THE START. 

In simulator, change standard_traffic = False to True to observe the implementation

### CODE REVIEW

**Comment by CraftinPark** [comment]
Task linked: [CU-86b17nztq Implement commands](https://app.clickup.com/t/86b17nztq)

**Comment by changoug** [comment]
Hello David, John and I reviewed your PR. It was pretty legit. We made some optimizations to your code, and we think it warrants a coding review session with you to go over what has changed. Great stuff man!

**Comment by CraftinPark** [comment]
There is also another bug with preset6 - we named the troubled car Lamborghini Reventon, and it seems to move erratically, sometimes backwards - you may need to run the same preset a couple times before you see the bug.

**Review by CraftinPark — CHANGES_REQUESTED** [review]
resolve mentioned bug with car sent backwards by command

**Comment by hyt152004** [comment]
> resolve mentioned bug with car sent backwards by command

the reason behind this problem comes from the kinematic equation. When the lambo takes a left turn, the opposing car also takes a right turn at the same time, causing the distance between the two cars to be less than 10 m. One of the prerequisites of this implementation is that the cars must be 10 m apart to correctly calculate the equation. When the traffic light implementation is completed along with the unprotected left and right implementations, I believe this shouldn't be a problem.

**Comment by changoug** [comment]
Would it affect the implementation if it's capped such that the velocity has to be equal to or greater than 0? Either way, we can test it with the traffic lights before taking any action.

**Comment by hyt152004** [comment]
> Would it affect the implementation if it's capped such that the velocity has to be equal to or greater than 0? Either way, we can test it with the traffic lights before taking any action.


yeah, unfortunately, it would completely break the code because of the following code.

safety_distance = 9
distance = distance_to_leading - safety_distance
required_deceleration = (final_velocity**2 - initial_velocity**2) / (2 * distance)
            
            
when vehicles are not placed at least 10m away, the distance becomes negative and causes the crazy scenario like the one with the Lamborghini

**Comment by changoug** [comment]
Hmmm I see. What if we only accept the change if the distance positive? Although I think I may be missing some context, as I can't quite understand why we can't just prevent the bad value from making the car's velocity from going negative. Let's call about this.

**Comment by CraftinPark** [comment]
> Hmmm I see. What if we only accept the change if the distance positive? Although I think I may be missing some context, as I can't quite understand why we can't just prevent the bad value from making the car's velocity from going negative. Let's call about this.

I concur, if we reach the case where bad things happen, let's just cut it off from the head. maybe if the distance is smaller than 10m, don't apply the command at all?

**Comment by changoug** [comment]
Just a heads up, try to use 'git restore .' to discard your changes by reseting your branch to the last commit (assuming you were trying to switch branches with unsaved changes).

**Comment by changoug** [comment]
@hyt152004 I added a change to not send the command if distance is negative. It seems to work for preset6, however I notice that it bugs out on rear_end_collision.json. It appears that the vehicles very close to each other (5m difference) and the one behind does not have enough time to react. Is this intended?

**Comment by hyt152004** [comment]
> @hyt152004 I added a change to not send the command if distance is negative. It seems to work for preset6, however I notice that it bugs out on rear_end_collision.json. It appears that the vehicles very close to each other (5m difference) and the one behind does not have enough time to react. Is this intended?

not intended but happened to be because of the nature of the kinematic equation.

i resolved it by hardcoded the velocity to 0 when the distance is <= 0. It then logs the situation.

**Comment by changoug** [comment]
Hey, just tested this on preset6. Seems to be running into the halting issue on a turn, albeit with a protected turn, we would not run into this issue.

**Review by changoug — COMMENTED** [review]
It should be good for protected left turns, will wait for John to take a look.

**Review by CraftinPark — APPROVED** [review]
very good job, thank you

**Pull request merged**
