### PR TITLE
Added timestamp that runs when simulation starts; resets when restart…

### PR DESCRIPTION
**Pull request by ptrjk0**
… button is clicked.

### CODE REVIEW

**Comment by CraftinPark** [comment]
Task linked: [CU-86b0rn6y3 Create timestamp visual](https://app.clickup.com/t/86b0rn6y3)

**Review by changoug — CHANGES_REQUESTED** [review]
The time should stop/restart when the simulation stops/restarts. Good stuff!

**Comment by CraftinPark** [comment]
Hi Peter just as an update, I can confirm the time doesn't start/stop, I think a file may not have been committed or pushed

**Review by changoug — APPROVED** [review]
This is good stuff.

**Pull request merged**
